[2024-02-12T10:53:32.303+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:53:32.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:53:32.306+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:53:32.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:53:32.309+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:53:32.309+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:53:32.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:53:32.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T10:54:02.450+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:02.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:54:02.454+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:02.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:02.458+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:02.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:54:02.458+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:02.475+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T10:54:32.822+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:32.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:54:32.830+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:32.829+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:32.836+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:54:32.833+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:54:32.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:54:32.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.082 seconds
[2024-02-12T10:55:02.966+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:02.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:55:02.971+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:02.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:02.976+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:02.974+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:55:02.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:02.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T10:55:33.173+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:33.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:55:33.178+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:33.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:33.183+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:55:33.182+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:55:33.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:55:33.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.035 seconds
[2024-02-12T10:56:03.356+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:03.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:56:03.361+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:03.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:03.365+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:03.364+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:56:03.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:03.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.035 seconds
[2024-02-12T10:56:33.411+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:33.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:56:33.415+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:33.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:33.421+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:56:33.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:56:33.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:56:33.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.042 seconds
[2024-02-12T10:57:04.003+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:04.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:57:04.005+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:04.005+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:04.010+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:04.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:57:04.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:04.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.035 seconds
[2024-02-12T10:57:34.427+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:34.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:57:34.431+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:34.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:34.440+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:57:34.436+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:57:34.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:57:34.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.058 seconds
[2024-02-12T10:58:04.789+0000] {processor.py:161} INFO - Started process (PID=540) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:04.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:58:04.796+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:04.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:04.805+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:04.803+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:58:04.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:04.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.052 seconds
[2024-02-12T10:58:34.947+0000] {processor.py:161} INFO - Started process (PID=596) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:34.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:58:34.956+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:34.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:34.964+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:58:34.962+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:58:34.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:58:34.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.053 seconds
[2024-02-12T10:59:05.062+0000] {processor.py:161} INFO - Started process (PID=652) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:05.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:59:05.071+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:05.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:05.079+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:05.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:59:05.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:05.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.050 seconds
[2024-02-12T10:59:35.501+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:35.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T10:59:35.524+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:35.523+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:35.535+0000] {logging_mixin.py:188} INFO - [2024-02-12T10:59:35.531+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T10:59:35.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T10:59:35.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.078 seconds
[2024-02-12T11:00:06.094+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:06.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:00:06.097+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:06.097+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:06.101+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:06.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:00:06.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:06.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T11:00:36.653+0000] {processor.py:161} INFO - Started process (PID=820) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:36.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:00:36.656+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:36.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:36.659+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:00:36.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:00:36.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:00:36.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.024 seconds
[2024-02-12T11:01:07.042+0000] {processor.py:161} INFO - Started process (PID=877) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:07.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:01:07.052+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:07.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:07.061+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:07.059+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:01:07.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:07.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.053 seconds
[2024-02-12T11:01:37.183+0000] {processor.py:161} INFO - Started process (PID=933) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:37.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:01:37.193+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:37.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:37.204+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:01:37.202+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:01:37.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:01:37.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.098 seconds
[2024-02-12T11:02:07.407+0000] {processor.py:161} INFO - Started process (PID=989) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:07.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:02:07.410+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:07.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:07.413+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:07.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:02:07.414+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:07.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T11:02:37.920+0000] {processor.py:161} INFO - Started process (PID=1045) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:37.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:02:37.924+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:37.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:37.929+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:02:37.927+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:02:37.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:02:37.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.042 seconds
[2024-02-12T11:03:08.254+0000] {processor.py:161} INFO - Started process (PID=1101) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:08.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:03:08.263+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:08.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:08.270+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:08.268+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:03:08.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:08.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.049 seconds
[2024-02-12T11:03:38.511+0000] {processor.py:161} INFO - Started process (PID=1157) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:38.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:03:38.514+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:38.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:38.518+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:03:38.517+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:03:38.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:03:38.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T11:04:08.924+0000] {processor.py:161} INFO - Started process (PID=1213) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:08.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:04:08.928+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:08.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:08.934+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:08.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:04:08.935+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:08.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.044 seconds
[2024-02-12T11:04:39.090+0000] {processor.py:161} INFO - Started process (PID=1269) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:39.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:04:39.094+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:39.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:39.098+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:04:39.097+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:04:39.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:04:39.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.037 seconds
[2024-02-12T11:05:09.992+0000] {processor.py:161} INFO - Started process (PID=1325) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:09.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:05:09.995+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:09.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:10.000+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:09.998+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:05:10.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:10.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.033 seconds
[2024-02-12T11:05:40.076+0000] {processor.py:161} INFO - Started process (PID=1380) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:40.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:05:40.078+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:40.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:40.081+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:05:40.081+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:05:40.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:05:40.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.026 seconds
[2024-02-12T11:06:00.697+0000] {processor.py:161} INFO - Started process (PID=1434) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:00.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:06:00.713+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:00.740+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:00.977+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.976+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:consumer_dag
[2024-02-12T11:06:00.991+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.990+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:consumer_dag
[2024-02-12T11:06:00.998+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.998+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:consumer_dag
[2024-02-12T11:06:00.998+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:00.998+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:06:01.013+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:01.013+0000] {dag.py:3058} INFO - Creating ORM DAG for consumer_dag
[2024-02-12T11:06:01.026+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:01.026+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:06:01.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.379 seconds
[2024-02-12T11:06:31.321+0000] {processor.py:161} INFO - Started process (PID=1490) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:31.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:06:31.325+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:31.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:31.333+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:06:31.352+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:31.352+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:06:31.373+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:06:31.372+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:06:31.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.075 seconds
[2024-02-12T11:07:01.439+0000] {processor.py:161} INFO - Started process (PID=1547) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:01.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:07:01.443+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:01.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:01.450+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:01.473+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:01.472+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:07:01.493+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:01.493+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:07:01.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.078 seconds
[2024-02-12T11:07:08.553+0000] {processor.py:161} INFO - Started process (PID=1548) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:08.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:07:08.565+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:08.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:08.592+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:08.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:07:08.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:08.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.158 seconds
[2024-02-12T11:07:39.660+0000] {processor.py:161} INFO - Started process (PID=1605) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:39.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:07:39.664+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:39.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:39.667+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:07:39.666+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:07:39.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:07:39.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T11:08:10.003+0000] {processor.py:161} INFO - Started process (PID=1662) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:10.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:08:10.007+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:10.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:10.010+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:10.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:08:10.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:10.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T11:08:40.852+0000] {processor.py:161} INFO - Started process (PID=1718) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:40.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:08:40.855+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:40.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:40.859+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:08:40.858+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:08:40.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:08:40.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T11:09:10.924+0000] {processor.py:161} INFO - Started process (PID=1774) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:10.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:09:10.927+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:10.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:10.930+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:10.929+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:09:10.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:10.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T11:09:41.385+0000] {processor.py:161} INFO - Started process (PID=1830) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:41.388+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:09:41.390+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:41.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:41.395+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:09:41.394+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:09:41.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:09:41.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.037 seconds
[2024-02-12T11:10:12.133+0000] {processor.py:161} INFO - Started process (PID=1886) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:12.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:10:12.134+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:12.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:12.137+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:12.136+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:10:12.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:12.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.025 seconds
[2024-02-12T11:10:42.201+0000] {processor.py:161} INFO - Started process (PID=1942) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:42.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:10:42.205+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:42.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:42.209+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:10:42.208+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:10:42.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:10:42.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.036 seconds
[2024-02-12T11:11:13.091+0000] {processor.py:161} INFO - Started process (PID=1998) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:13.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:11:13.094+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:13.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:13.099+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:13.098+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:11:13.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:13.119+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.034 seconds
[2024-02-12T11:11:43.261+0000] {processor.py:161} INFO - Started process (PID=2053) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:43.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:11:43.265+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:43.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:43.275+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:11:43.271+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:11:43.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:11:43.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.075 seconds
[2024-02-12T11:12:13.556+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:13.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:12:13.558+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:13.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:13.563+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:13.562+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:12:13.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:13.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T11:12:43.936+0000] {processor.py:161} INFO - Started process (PID=2166) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:43.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:12:43.940+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:43.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:43.944+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:12:43.943+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:12:43.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:12:43.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.036 seconds
[2024-02-12T11:13:14.312+0000] {processor.py:161} INFO - Started process (PID=2222) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:14.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:13:14.315+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:14.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:14.322+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:14.320+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:13:14.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:14.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.053 seconds
[2024-02-12T11:13:45.234+0000] {processor.py:161} INFO - Started process (PID=2277) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:45.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:13:45.237+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:45.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:45.243+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:13:45.241+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:13:45.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:13:45.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.041 seconds
[2024-02-12T11:14:15.595+0000] {processor.py:161} INFO - Started process (PID=2333) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:15.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:14:15.599+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:15.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:15.604+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:15.603+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:14:15.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:15.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T11:14:45.956+0000] {processor.py:161} INFO - Started process (PID=2389) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:45.957+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:14:45.957+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:45.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:45.960+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:14:45.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:14:45.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:14:45.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.023 seconds
[2024-02-12T11:15:16.261+0000] {processor.py:161} INFO - Started process (PID=2445) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:16.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:15:16.263+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:16.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:16.267+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:16.266+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:15:16.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:16.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.026 seconds
[2024-02-12T11:15:46.930+0000] {processor.py:161} INFO - Started process (PID=2501) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:46.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:15:46.934+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:46.933+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:46.939+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:15:46.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:15:46.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:15:46.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.044 seconds
[2024-02-12T11:16:17.392+0000] {processor.py:161} INFO - Started process (PID=2557) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:17.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:16:17.397+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:17.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:17.403+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:17.402+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:16:17.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:17.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T11:16:47.634+0000] {processor.py:161} INFO - Started process (PID=2613) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:47.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:16:47.637+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:47.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:47.641+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:16:47.640+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:16:47.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:16:47.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.043 seconds
[2024-02-12T11:17:18.134+0000] {processor.py:161} INFO - Started process (PID=2669) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:18.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:17:18.136+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:18.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:18.141+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:18.139+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:17:18.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:18.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.048 seconds
[2024-02-12T11:17:48.443+0000] {processor.py:161} INFO - Started process (PID=2725) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:48.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:17:48.445+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:48.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:48.447+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:17:48.446+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:17:48.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:17:48.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.024 seconds
[2024-02-12T11:18:18.735+0000] {processor.py:161} INFO - Started process (PID=2781) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:18.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:18:18.736+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:18.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:18.740+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:18.739+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:18:18.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:18.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.026 seconds
[2024-02-12T11:18:49.322+0000] {processor.py:161} INFO - Started process (PID=2846) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:49.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:18:49.325+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:49.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:49.330+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:18:49.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:18:49.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:18:49.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.034 seconds
[2024-02-12T11:19:19.814+0000] {processor.py:161} INFO - Started process (PID=2939) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:19.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:19:19.816+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:19.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:19.822+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:19.821+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:19:19.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:19.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.030 seconds
[2024-02-12T11:19:50.367+0000] {processor.py:161} INFO - Started process (PID=2995) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:50.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:19:50.370+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:50.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:50.376+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:19:50.375+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T11:19:50.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:19:50.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.040 seconds
[2024-02-12T11:20:20.914+0000] {processor.py:161} INFO - Started process (PID=3089) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:20.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:20:20.917+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:20.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:20.966+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:20.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 6, in <module>
    from kafka import KafkaConsumer
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/__init__.py", line 23, in <module>
    from kafka.producer import KafkaProducer
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/__init__.py", line 4, in <module>
    from .simple import SimpleProducer
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^
SyntaxError: invalid syntax
[2024-02-12T11:20:20.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:20.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.081 seconds
[2024-02-12T11:20:51.603+0000] {processor.py:161} INFO - Started process (PID=3145) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:51.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:20:51.606+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:51.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:51.689+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:20:51.823+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:51.822+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:20:51.851+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:20:51.851+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:20:51.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.288 seconds
[2024-02-12T11:21:22.473+0000] {processor.py:161} INFO - Started process (PID=3206) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:22.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:21:22.475+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:22.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:22.563+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:22.627+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:22.627+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:21:22.664+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:22.663+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:21:22.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.214 seconds
[2024-02-12T11:21:53.039+0000] {processor.py:161} INFO - Started process (PID=3262) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:53.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:21:53.050+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:53.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:53.260+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:21:53.355+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:53.355+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:21:53.419+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:21:53.419+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:21:53.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.433 seconds
[2024-02-12T11:22:23.967+0000] {processor.py:161} INFO - Started process (PID=3318) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:23.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:22:23.972+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:23.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:24.173+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:24.252+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:24.250+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:22:24.334+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:24.333+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:22:24.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.438 seconds
[2024-02-12T11:22:27.047+0000] {processor.py:161} INFO - Started process (PID=3319) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:27.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:22:27.049+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:27.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:27.174+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:22:27.895+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:27.891+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:22:27.978+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:22:27.977+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:22:28.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 1.032 seconds
[2024-02-12T11:23:07.205+0000] {processor.py:161} INFO - Started process (PID=3374) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:23:07.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:23:07.225+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:23:07.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:23:07.557+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:23:07.633+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:23:07.631+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:23:07.710+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:23:07.710+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T11:23:07.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.585 seconds
[2024-02-12T11:30:27.100+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:30:27.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T11:30:27.102+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:30:27.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:30:27.186+0000] {processor.py:840} INFO - DAG(s) 'consumer_dag' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T11:30:27.253+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:30:27.253+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T11:30:27.309+0000] {logging_mixin.py:188} INFO - [2024-02-12T11:30:27.309+0000] {dag.py:3823} INFO - Setting next_dagrun for consumer_dag to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T11:30:27.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.238 seconds
[2024-02-12T13:50:18.837+0000] {processor.py:161} INFO - Started process (PID=1700) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:50:18.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:50:18.839+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:50:18.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:50:18.845+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:50:18.844+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:50:18.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:50:18.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.031 seconds
[2024-02-12T13:50:49.372+0000] {processor.py:161} INFO - Started process (PID=1756) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:50:49.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:50:49.379+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:50:49.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:50:49.389+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:50:49.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:50:49.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:50:49.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.048 seconds
[2024-02-12T13:51:19.552+0000] {processor.py:161} INFO - Started process (PID=1812) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:51:19.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:51:19.554+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:51:19.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:51:19.559+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:51:19.558+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:51:19.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:51:19.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.042 seconds
[2024-02-12T13:51:50.531+0000] {processor.py:161} INFO - Started process (PID=1868) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:51:50.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:51:50.533+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:51:50.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:51:50.538+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:51:50.537+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:51:50.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:51:50.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.039 seconds
[2024-02-12T13:52:21.020+0000] {processor.py:161} INFO - Started process (PID=1924) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:52:21.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:52:21.023+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:52:21.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:52:21.028+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:52:21.027+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:52:21.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:52:21.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.036 seconds
[2024-02-12T13:52:51.534+0000] {processor.py:161} INFO - Started process (PID=1979) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:52:51.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:52:51.538+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:52:51.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:52:51.543+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:52:51.542+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:52:51.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:52:51.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.040 seconds
[2024-02-12T13:53:21.942+0000] {processor.py:161} INFO - Started process (PID=2035) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:53:21.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:53:21.945+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:53:21.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:53:21.950+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:53:21.949+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:53:21.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:53:21.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T13:53:52.206+0000] {processor.py:161} INFO - Started process (PID=2091) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:53:52.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:53:52.211+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:53:52.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:53:52.222+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:53:52.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:53:52.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:53:52.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.049 seconds
[2024-02-12T13:54:22.552+0000] {processor.py:161} INFO - Started process (PID=2148) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:54:22.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:54:22.555+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:54:22.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:54:22.560+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:54:22.559+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:54:22.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:54:22.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.041 seconds
[2024-02-12T13:54:53.208+0000] {processor.py:161} INFO - Started process (PID=2205) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:54:53.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:54:53.209+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:54:53.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:54:53.213+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:54:53.212+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:54:53.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:54:53.232+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.028 seconds
[2024-02-12T13:55:23.751+0000] {processor.py:161} INFO - Started process (PID=2261) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:55:23.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:55:23.753+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:55:23.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:55:23.757+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:55:23.756+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:55:23.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:55:23.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.029 seconds
[2024-02-12T13:55:53.829+0000] {processor.py:161} INFO - Started process (PID=2318) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:55:53.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:55:53.835+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:55:53.834+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:55:53.843+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:55:53.842+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:55:53.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:55:53.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.048 seconds
[2024-02-12T13:56:24.128+0000] {processor.py:161} INFO - Started process (PID=2374) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:56:24.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:56:24.131+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:56:24.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:56:24.139+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:56:24.137+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:56:24.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:56:24.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.041 seconds
[2024-02-12T13:56:54.284+0000] {processor.py:161} INFO - Started process (PID=2430) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:56:54.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:56:54.289+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:56:54.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:56:54.297+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:56:54.296+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:56:54.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:56:54.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.049 seconds
[2024-02-12T13:57:24.996+0000] {processor.py:161} INFO - Started process (PID=2486) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:57:24.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:57:24.999+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:57:24.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:57:25.005+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:57:25.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:57:25.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:57:25.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.043 seconds
[2024-02-12T13:57:55.666+0000] {processor.py:161} INFO - Started process (PID=2543) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:57:55.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:57:55.671+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:57:55.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:57:55.677+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:57:55.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:57:55.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:57:55.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.042 seconds
[2024-02-12T13:58:25.997+0000] {processor.py:161} INFO - Started process (PID=2599) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:58:25.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:58:26.002+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:58:26.001+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:58:26.013+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:58:26.011+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:58:26.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:58:26.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.050 seconds
[2024-02-12T13:58:56.291+0000] {processor.py:161} INFO - Started process (PID=2655) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:58:56.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:58:56.293+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:58:56.293+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:58:56.300+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:58:56.298+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:58:56.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:58:56.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.046 seconds
[2024-02-12T13:59:26.698+0000] {processor.py:161} INFO - Started process (PID=2711) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:59:26.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:59:26.702+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:59:26.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:59:26.709+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:59:26.707+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:59:26.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:59:26.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.058 seconds
[2024-02-12T13:59:57.665+0000] {processor.py:161} INFO - Started process (PID=2767) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:59:57.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T13:59:57.667+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:59:57.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:59:57.675+0000] {logging_mixin.py:188} INFO - [2024-02-12T13:59:57.673+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/consumer_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/consumer_dag.py", line 12, in <module>
    from dags.consumer import main
  File "/opt/airflow/dags/consumer.py", line 1, in <module>
    from kafka import KafkaConsumer
ModuleNotFoundError: No module named 'kafka'
[2024-02-12T13:59:57.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T13:59:57.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.060 seconds
[2024-02-12T14:00:25.551+0000] {processor.py:161} INFO - Started process (PID=2815) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:00:25.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:00:25.554+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:00:25.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:00:25.571+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:00:25.732+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:00:25.732+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:00:25.754+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:00:25.753+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:00:25.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.231 seconds
[2024-02-12T14:00:55.872+0000] {processor.py:161} INFO - Started process (PID=2873) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:00:55.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:00:55.873+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:00:55.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:00:55.883+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:00:55.900+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:00:55.900+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:00:55.922+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:00:55.922+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:00:55.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.071 seconds
[2024-02-12T14:01:26.677+0000] {processor.py:161} INFO - Started process (PID=2927) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:01:26.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:01:26.680+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:01:26.680+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:01:26.693+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:01:26.715+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:01:26.715+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:01:26.741+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:01:26.740+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:01:26.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.089 seconds
[2024-02-12T14:01:56.984+0000] {processor.py:161} INFO - Started process (PID=2983) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:01:56.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:01:56.988+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:01:56.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:01:57.000+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:01:57.023+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:01:57.022+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:01:57.046+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:01:57.046+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:01:57.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.085 seconds
[2024-02-12T14:02:27.432+0000] {processor.py:161} INFO - Started process (PID=3040) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:02:27.436+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:02:27.442+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:02:27.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:02:27.474+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:02:27.532+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:02:27.531+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:02:27.631+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:02:27.631+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:02:27.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.296 seconds
[2024-02-12T14:02:58.388+0000] {processor.py:161} INFO - Started process (PID=3096) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:02:58.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:02:58.392+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:02:58.391+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:02:58.407+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:02:58.439+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:02:58.439+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:02:58.473+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:02:58.473+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:02:58.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.118 seconds
[2024-02-12T14:03:28.643+0000] {processor.py:161} INFO - Started process (PID=3152) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:03:28.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:03:28.645+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:03:28.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:03:28.656+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:03:28.679+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:03:28.679+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:03:28.710+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:03:28.710+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:03:28.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.091 seconds
[2024-02-12T14:03:59.251+0000] {processor.py:161} INFO - Started process (PID=3209) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:03:59.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:03:59.253+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:03:59.253+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:03:59.265+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:03:59.291+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:03:59.291+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:03:59.327+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:03:59.326+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:03:59.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.121 seconds
[2024-02-12T14:04:29.541+0000] {processor.py:161} INFO - Started process (PID=3265) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:04:29.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:04:29.551+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:04:29.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:04:29.572+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:04:29.631+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:04:29.630+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:04:29.720+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:04:29.720+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:04:29.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.225 seconds
[2024-02-12T14:05:58.611+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:05:58.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:05:58.614+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:05:58.634+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:05:58.917+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.916+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:kafka
[2024-02-12T14:05:58.929+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.929+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:kafka
[2024-02-12T14:05:58.938+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.937+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:kafka
[2024-02-12T14:05:58.938+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.938+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:05:58.951+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.951+0000] {dag.py:3058} INFO - Creating ORM DAG for kafka
[2024-02-12T14:05:58.963+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:05:58.963+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T14:05:58.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.376 seconds
[2024-02-12T14:06:29.789+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:06:29.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:06:29.793+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:06:29.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:06:29.802+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:06:29.822+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:06:29.822+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:06:29.845+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:06:29.845+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-11 00:00:00+00:00, run_after=2024-02-12 00:00:00+00:00
[2024-02-12T14:06:29.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.079 seconds
[2024-02-12T14:07:00.650+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:07:00.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:07:00.655+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:07:00.654+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:07:00.666+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:07:00.687+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:07:00.687+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:07:00.712+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:07:00.712+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:07:00.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.093 seconds
[2024-02-12T14:07:31.306+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:07:31.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:07:31.312+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:07:31.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:07:31.326+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:07:31.346+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:07:31.346+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:07:31.373+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:07:31.372+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:07:31.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.100 seconds
[2024-02-12T14:08:01.940+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:08:01.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:08:01.944+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:08:01.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:08:01.954+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:08:01.975+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:08:01.975+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:08:02.001+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:08:02.001+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:08:02.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.086 seconds
[2024-02-12T14:08:32.321+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:08:32.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:08:32.327+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:08:32.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:08:32.340+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:08:32.361+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:08:32.360+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:08:32.385+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:08:32.385+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:08:32.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.091 seconds
[2024-02-12T14:09:02.653+0000] {processor.py:161} INFO - Started process (PID=371) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:09:02.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:09:02.658+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:09:02.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:09:02.672+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:09:02.693+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:09:02.692+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:09:02.715+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:09:02.715+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:09:02.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.089 seconds
[2024-02-12T14:09:33.010+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:09:33.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:09:33.020+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:09:33.018+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:09:33.050+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:09:33.120+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:09:33.119+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:09:33.226+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:09:33.225+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:09:33.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.284 seconds
[2024-02-12T14:10:44.408+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:10:44.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:10:44.411+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:10:44.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:10:44.431+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:10:44.700+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:10:44.699+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:10:44.728+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:10:44.728+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:10:44.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.348 seconds
[2024-02-12T14:11:15.111+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:11:15.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:11:15.120+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:11:15.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:11:15.139+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:11:15.183+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:11:15.182+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:11:15.263+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:11:15.263+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:11:15.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.212 seconds
[2024-02-12T14:11:45.391+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:11:45.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:11:45.396+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:11:45.395+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:11:45.408+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:11:45.428+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:11:45.427+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:11:45.449+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:11:45.449+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:11:45.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.081 seconds
[2024-02-12T14:12:15.992+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:12:15.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:12:15.999+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:12:15.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:12:16.022+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:12:16.075+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:12:16.074+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:12:16.134+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:12:16.133+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:12:16.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.198 seconds
[2024-02-12T14:12:46.817+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:12:46.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:12:46.826+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:12:46.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:12:46.861+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:12:46.929+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:12:46.928+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:12:46.999+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:12:46.998+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:12:47.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.239 seconds
[2024-02-12T14:13:17.119+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:13:17.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:13:17.123+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:13:17.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:13:17.137+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:13:17.165+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:13:17.164+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:13:17.194+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:13:17.193+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:13:17.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.105 seconds
[2024-02-12T14:13:47.619+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:13:47.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/consumer_dag.py for tasks to queue
[2024-02-12T14:13:47.627+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:13:47.626+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:13:47.647+0000] {processor.py:840} INFO - DAG(s) 'kafka' retrieved from /opt/airflow/dags/consumer_dag.py
[2024-02-12T14:13:47.686+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:13:47.685+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-12T14:13:47.728+0000] {logging_mixin.py:188} INFO - [2024-02-12T14:13:47.728+0000] {dag.py:3823} INFO - Setting next_dagrun for kafka to 2024-02-12 00:00:00+00:00, run_after=2024-02-13 00:00:00+00:00
[2024-02-12T14:13:47.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/consumer_dag.py took 0.147 seconds
